#"config.json" need to be included by using --configfile options when running snakemake

#Reads sample name from snakemake config 'target' specified by -C (eg. -C 'target=FCD105')
TARGET=config["target"]

#Includes snakemake rules
include:
    "./panelTest.rules"

#Target data rule
rule all:
    input:
        #Somatic mutation calling
        expand("{ALG}/{TARGET}.passed.EB.variant_annotation.{TYPE}_functional_annotation.inhouseF_fix_final.vcf", TARGET=TARGET, ALG=["mutect", "strelka"], TYPE=["HIGH", "MODERATE"])
